### ISSUE TITLE
Combine imbDRL with a Feature Selection strategy

### ISSUE THREAD

**Issue by iMac-ant** [Denbergvanthijs/imbDRL#9]
Hi @Denbergvanthijs, I hope you are fine! 
Have you ever tried using your classifier with feature selection procedures? In such an application, I am experiencing the following problem: with each iteration to which a new feature sub-set corresponds, ivi a new input layer size for the network, I get an error back. Specifically, it is as if it expects a number of input data equal to the number of features in the previous iteration. So, for example, assuming, x_train.shape[1] = 17 for i = 1, the compilation of the model fails if x_train.shape[1] = 16 for i = 2. Could you give me some clarification on this?

**Comment by iMac-ant** [comment]
I solved this issue by forcing the input_dim to xtrain.shape[1] at the first layer and removing the argument self.train_env.observation_spec() when you declared self.q_net.

**Comment by Denbergvanthijs** [comment]
The number of features needs to match the input layer dimension of course but I see now that you change the input layer size at each iteration so indeed your solution should work, good luck!

Btw, does this mean that you need to relearn all weights connected to the input layer for each iteration or are you only removing the unselected nodes each iteration instead of creating a new input layer with random weights?
